spec-version: 0.30.0
name: postgresql-dynamic
version: 0.1
synopsis:            Read rows from Postgres into 'Map Text Dynamic'
description: Load all columns returned by Postgres into a generic key-value map.  This is useful for interactive development, when exploring the database schema, or before it's clear which columns will be needed.
github:            bergey/postgresql-dynamic
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
  source-dirs: [src]

dependencies:
    - base >= 4.11 && < 4.13
    - aeson ^>= 1.4.2.0
    - bytestring ^>= 0.10.8.2
    - containers >= 0.5.11.0 && < 0.7
    - postgresql-libpq ^>= 0.9.4.2
    - postgresql-simple ^>= 0.6.2
    - text ^>= 1.2.3.1
    - time ^>= 1.8.0.2
    - transformers ^>= 0.5.5.0
    - uuid ^>= 1.3.13
